# This workflow will upload a Godot Asset to the Asset Library
# everytime a tag is pushed or a release is published.

name: Build and publish Godot addon

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags:
      - 'godot-dice-roller-[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish new version to asset lib
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Godot Asset Lib Upload
      shell: bash
      run: |
        echo "GODOT_ASSET_LIB_USER=${{ secrets.GODOT_ASSET_LIB_USER }}" >> .env
        echo "GODOT_ASSET_LIB_PASSWORD=${{ secrets.GODOT_ASSET_LIB_PASSWORD }}" >> .env
        pip install --user godot-asset-library-client
        godot-asset-library-client upload tools/assetlib.yaml --send-previews --do

# vim: et sw=2 ts=2
