name: "godot-ci build-and-release"

on:
  workflow_dispatch:
  push:
    tags:
      - '.+-[0-9]+.[0-9]+.[0-9]+'

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: godot-dice-roller
  PROJECT_PATH: .

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Templates
        run: |

          find / | grep odot

          VERSION="${{ env.GODOT_VERSION }}"
          VERSION_TAG="${VERSION}-stable"
          FILE_NAME="Godot_v${VERSION_TAG}_export_templates.tpz"
          URL="https://github.com/godotengine/godot/releases/download/${VERSION_TAG}/${FILE_NAME}"
          DEST="$HOME/.local/share/godot/export_templates/${VERSION_TAG}"

          mkdir -p "$DEST"
          wget --no-verbose "${URL}" -O templates.tpz
          unzip templates.tpz -d "$DEST"

          ls ${DEST}/..
          ls ${DEST}

      - name: GitHub Tag Name
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Setup folders
        run: |
          mkdir -p .godot/editor .godot/imported
          mkdir -v -p build/windows
          mkdir -v -p build/web
          mkdir -v -p build/linux
          mkdir -v -p build/mac
          echo "$GITHUB_REF" > build/version.txt
      - name: Web Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "HTML5" ../build/web/index.html
      - name: Windows Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Linux Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Mac Build
        run: |
          cd $PROJECT_PATH
          ls
          godot -v --headless --export-release "Mac OSX" ../build/mac/$EXPORT_NAME.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-builds
          path: build
  release-itchio:
    name: To itchio
    needs: build  
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:latest
    steps:
      - name: Download build 
        uses: actions/download-artifact@v4
        with:
          name: my-builds
      - name: Listar archivos en la carpeta
        run: |
          ls
      - name: Upload bundles
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
        run: |
          echo $GITHUB_REF_NAME
          butler push web $ITCH_USER/$ITCH_GAME:html5 --userversion $GITHUB_REF_NAME
          butler push windows $ITCH_USER/$ITCH_GAME:windows --userversion $GITHUB_REF_NAME
          butler push linux $ITCH_USER/$ITCH_GAME:linux --userversion $GITHUB_REF_NAME
          butler push mac $ITCH_USER/$ITCH_GAME:mac --userversion $GITHUB_REF_NAME
