name: Godot GUT Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4.1
  GODOT_MIRROR: https://github.com/godotengine/godot/releases/download
  GODOT_BASE: Godot_v4.4.1-stable_linux.x86_64  # centralized base name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup symlink for GUT
      run: |
        mkdir -p addons
        ln -sf ../externals/gut/addons/gut addons/gut

    - name: Download Godot Headless
      run: |
        wget "${{ env.GODOT_MIRROR }}/${{ env.GODOT_VERSION }}-stable/${{ env.GODOT_BASE }}.zip"
        unzip "${{ env.GODOT_BASE }}.zip" -d godot
        chmod +x "godot/${{ env.GODOT_BASE }}"

    - name: Define GODOT binary path
      run: echo "GODOT=./godot/${{ env.GODOT_BASE }}" >> $GITHUB_ENV

    - name: Preload project (import assets)
      run: $GODOT --headless --import --path . --quit || true # always fails

    - name: Run GUT tests
      run: $GODOT --headless -s addons/gut/gut_cmdln.gd -gprefix='' -gsuffix='_test.gd' -gdir tests --quit --verbose
