name: Godot GUT Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup symlink for GUT
        run: |
          mkdir -p addons
          ln -sf ../externals/gut/addons/gut addons/gut

      - name: Run GUT tests using Godot docker image
        uses: addnab/docker-run-action@v3
        with:
          image: godotengine/godot:4.4.1-linux-headless
          options: --rm
          run: >
            godot --headless
                  -s addons/gut/gut_cmdln.gd
                  -gprefix=''
                  -gsuffix='_test.gd'
                  -gdir tests
                  --quit
